spring:
  datasource: 
    url: jdbc:postgresql://ec2-107-21-94-185.compute-1.amazonaws.com/d1rb4ibu8ghpfn?sslmode=require
    username: vuoynmbvfnpjgc
    password: 94720ef8e26e6f44fb73ce4afaeeb7d1b564e1ce1b76da6a07cfdce40c89c1ed
    platform: postgres
    driverClassName: org.postgresql.Driver
  initializacion-mode: always
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
        #ddl-auto: update
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
server:
  max-http-header-size: 65236
  
  logging:
    config: classpath:logback-spring.xml


     
#cron.expression.coordinates.all: 0 0 2 * * ?
cron.expression.coordinates.all: 0/5 * * * * ?