spring:
  datasource: 
    url: jdbc:postgresql://ec2-54-221-214-3.compute-1.amazonaws.com/d4o6npqeq5n615?sslmode=require
    username: zgbamjlcwwahod
    password: 84f7045beaf6f0ece2b3ad284126b2c3102975c907163042cbb5078e906c8505
    platform: postgres
    driverClassName: org.postgresql.Driver
  initializacion-mode: always
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
        #ddl-auto: update
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
server:
  max-http-header-size: 65236
  
  logging:
    config: classpath:logback-spring.xml


     
#cron.expression.coordinates.all: 0 0 2 * * ?
cron.expression.coordinates.all: 0/5 * * * * ?