spring:
  datasource: 
    url: jdbc:postgresql://ec2-54-221-195-148.compute-1.amazonaws.com:5432/de04rbbandbir0?sslmode=require
    username: ewhopjtxjfenzh
    password: f2626ad66a3b1128113fd8e78533a976022001511f6ad2ec189681f61cc55f97
    platform: postgres
    driverClassName: org.postgresql.Driver
  initializacion-mode: always
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
        #ddl-auto: update
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
server:
  max-http-header-size: 65236
  
  logging:
    config: classpath:logback-spring.xml


     
#cron.expression.coordinates.all: 0 0 2 * * ?
cron.expression.coordinates.all: 0/5 * * * * ?